version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directories:
    - "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
