---
###############################################################
# These are the rules used for                                #
# linting all the yaml files in the stack                     #
# NOTE:                                                       #
# You can disable line with:                                  #
# # yamllint disable-line                                     #
# Rules: https://yamllint.readthedocs.io/en/stable/rules.html #
###############################################################

# Exclude not required files
ignore-from-file:
  - .gitignore
  - .yamlignore

rules:
  braces:
    level: warning
    min-spaces-inside: 1
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  brackets:
    level: warning
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: -1
    max-spaces-inside-empty: -1
  colons:
    level: warning
    max-spaces-before: 0
    max-spaces-after: -1
  commas:
    level: warning
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1
  comments:
    level: warning
    require-starting-space: true
    min-spaces-from-content: 1
  comments-indentation:
    level: warning
  document-end: disable
  document-start: disable
  empty-lines:
    level: warning
    max: 2
    max-start: 0
    max-end: 2
  hyphens:
    level: warning
    max-spaces-after: 1
  indentation:
    spaces: 2
    indent-sequences: false
    check-multi-line-strings: false
  key-duplicates: enable
  line-length: disable
  new-line-at-end-of-file: disable
  new-lines:
    type: unix
  octal-values:
    forbid-implicit-octal: false
    forbid-explicit-octal: false
  trailing-spaces: enable
  truthy: disable
