paths:
  .github/workflows/**/*.{yml,yaml}:
    ignore:
      - 'shellcheck reported issue in this script: SC2086:info.+'
      - 'shellcheck reported issue in this script: SC2002:style.+'
  .github/workflows/build.yaml:
    ignore:
      - 'property "postfix" is not defined in object type {}'
      - 'property "context" is not defined in object type {file: string; name: string}'
