apiVersion: v1
kind: Secret
metadata:
  name: env-checker-oidc-secret
  labels:
    app.kubernetes.io/name: '{{ .Values.SERVICE_NAME }}'
    app.kubernetes.io/part-of: '{{ .Values.APPLICATION_NAME }}'
    app.kubernetes.io/managed-by: '{{ .Values.MANAGED_BY }}'
type: nginx.org/oidc
{{- if and .Values.ENVCHECKER_KEYCLOACK_CLIENT_SECRET .Values.OPS_IDP_URL }}
data:
  client-secret: {{ .Values.ENVCHECKER_KEYCLOACK_CLIENT_SECRET | b64enc }}
{{- end }}
