apiVersion: v1
kind: Secret
metadata:
  name: env-checker-ui-access-token
  labels:
    app.kubernetes.io/name: '{{ .Values.SERVICE_NAME }}'
    app.kubernetes.io/part-of: '{{ .Values.APPLICATION_NAME }}'
    app.kubernetes.io/managed-by: '{{ .Values.MANAGED_BY }}'
type: Opaque
stringData:
{{- if .Values.OPS_IDP_URL }}
  access-token: ''
{{- else }}
  access-token: {{ .Values.ENVIRONMENT_CHECKER_UI_ACCESS_TOKEN | default (randAlphaNum 32) | lower }}
{{- end }}
