name: Build Artifacts

on:
  release:
    types: [created]
  push:
    branches:
      - '**'
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/build.yaml'
      - '!docs/**'
  workflow_dispatch:
    inputs:
      postfix:
        description: 'Postfix for tag name'
        required: false

permissions:
  contents: read

env:
  RAW_TAG_NAME: ${{ github.event.release.tag_name != '' && github.event.release.tag_name || github.ref_name }}
  TAG_POSTFIX: ${{ inputs.postfix || '' }}

jobs:
  multiplatform_build:
    permissions:
      actions: read          # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      contents: read         # for actions/checkout to fetch code
      packages: write        # for publishing docker image to ghcr.io registry
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    strategy:
      fail-fast: false
      matrix:
        component:
          - name: qubership-env-checker
            context: .
            description: Environments Checker Base image
            file: Dockerfile
        platform:
          # For runners details see https://docs.github.com/en/actions/concepts/runners/github-hosted-runners#runner-images
          - name: amd64
            runner: ubuntu-latest
          - name: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.platform.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Prepare for multiplatform build
        run: |
          platform=${{ matrix.platform.name }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Compute repository name
        id: owner
        run: |
          OWNER="${{ github.repository_owner }}"
          OWNER="${OWNER,,}"
          OWNER=$(echo "$OWNER" | sed -E 's/[^a-z0-9._-]+/-/g')
          echo "owner=$OWNER" >> $GITHUB_OUTPUT

      - name: Compute image tag
        id: tag
        run: |
          NAME="${RAW_TAG_NAME}"
          # sanitize to be a valid docker tag: lowercase, replace invalid chars, max length 128
          NAME="${NAME,,}"
          NAME=$(echo "$NAME" | sed -E 's/[^a-z0-9._-]+/-/g')
          # optional postfix
          if [ -n "${TAG_POSTFIX}" ]; then
            POSTFIX=$(echo "${TAG_POSTFIX}" | sed -E 's/[^a-z0-9._-]+/-/g')
            NAME="${NAME}-${POSTFIX}"
          fi
          echo "tag=$NAME" >> $GITHUB_OUTPUT

      - name: Set image name
        run: |
          echo "FULL_IMAGE_NAME=ghcr.io/${{ steps.owner.outputs.owner }}/${{ matrix.component.name }}" >>${GITHUB_ENV}
        env:
          IMAGE_NAME: '${{ github.repository }}'

      - name: Get short SHA
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          images: "${{ env.FULL_IMAGE_NAME }}"
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=git-
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=${{ github.ref == 'refs/heads/main' }}

      - name: Login to Docker Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          password: ${{secrets.GITHUB_TOKEN}}
          registry: ghcr.io
          username: ${GITHUB_ACTOR}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Build and push
        id: build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: '${{ matrix.component.context }}'
          file: '${{ matrix.component.file }}'
          labels: ${{ steps.meta.outputs.labels }}
          # load: true
          no-cache: true
          outputs: type=image,name=${{ env.FULL_IMAGE_NAME }},push-by-digest=true,name-canonical=true,push=true
          platforms: 'linux/${{ matrix.platform.name }}'
          provenance: false
          push: "${{ vars.PUBLISH_DOCKER_IMAGES == 'true' }}"
          build-args: |
            BUILD_HASH=${{ github.sha }}

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: digests-${{ matrix.component.name }}-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    permissions:
      actions: read
      contents: read
      packages: write
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        component:
          - name: qubership-env-checker
            context: .
            description: Environments Checker Base image
            file: Dockerfile
    runs-on: ubuntu-latest
    needs:
      - multiplatform_build
    steps:
      - name: Compute repository name
        id: owner
        run: |
          OWNER="${{ github.repository_owner }}"
          OWNER="${OWNER,,}"
          OWNER=$(echo "$OWNER" | sed -E 's/[^a-z0-9._-]+/-/g')
          echo "owner=$OWNER" >> $GITHUB_OUTPUT

      - name: Set image name
        run: |
          echo "FULL_IMAGE_NAME=ghcr.io/${{ steps.owner.outputs.owner }}/${{ matrix.component.name }}" >>${GITHUB_ENV}
        env:
          IMAGE_NAME: '${{ github.repository }}'

      - name: Download digests
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-${{ matrix.component.name }}-*
          merge-multiple: true

      - name: Login to Docker Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          password: ${{secrets.GITHUB_TOKEN}}
          registry: ghcr.io
          username: ${GITHUB_ACTOR}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          images: "${{ env.FULL_IMAGE_NAME }}"
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=git-
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=${{ github.ref == 'refs/heads/main' }}

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        # shellcheck disable=SC2046
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.FULL_IMAGE_NAME }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect "${{ env.FULL_IMAGE_NAME }}:${{ steps.meta.outputs.version }}"
